package com.example.poctransfer.enums;

public enum ConceptType {
    RENTALS,
    INSTALLMENTS,
    EXPENSES,
    BILL,
    LOAN,
    INSURANCE,
    FEE,
    PAYROLL,
    VARIOUS,
    FUNDS_RESCUE,
    FUNDS_SUBSCRIPTION,
    REAL_ESTATE_OPERATION,
    USUAL_REAL_ESTATE_OPERATION,
    USUAL_REGISTRABLE_PROPERTY,
    NOT_SUAL_REGISTRABLE_PROPERTY,
    SUBSCRIPTION_NEGOTIABLE_OBLIGATIONS,
    SOCIAL_SECURITY_REFUND,
    INSURANCE_CLAIMS,
    CAPITAL_CONTRIBUTIONS,
    STATUS_EXPROPRIATIONS_OR_OTHERS
}
