package com.example.poctransfer.enums;

public enum OperationType {
    COMMON,
    COMMON_BCRA,
    JUDICIAL,
    BCRA_ACCOUNTS,
    MUTUAL_FOUND_TRUST_SUSCRIPTION,
    FIXED_TERM_DEPOSITS,
    SECURITIES_TRANSACTIONS,
    MUTUAL_FOUND_TRUST_REDEMPTION,
    SECURITIES_INCOME_AMORTIZATION,
    UNDEFINED
}
